# Generated by Django 4.1.3 on 2022-12-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='setorTunai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('No_Tabungan', models.CharField(max_length=30)),
                ('Tanggal', models.DateField()),
                ('Alamat', models.TextField()),
                ('N_Penyetoran', models.CharField(max_length=20)),
                ('Terbilang', models.CharField(max_length=50)),
                ('Nama_Penyetor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tarikTunai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('No_Tabungan', models.CharField(max_length=30)),
                ('Tanggal', models.DateField()),
                ('Alamat', models.TextField()),
                ('N_Penarikan', models.CharField(max_length=20)),
                ('Terbilang', models.CharField(max_length=50)),
                ('Nama_Penarik', models.CharField(max_length=50)),
            ],
        ),
    ]
