# Generated by Django 4.1.3 on 2022-12-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gadai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=30)),
                ('Nik', models.CharField(max_length=30)),
                ('Alamat', models.TextField()),
                ('Barang_Jaminan', models.CharField(max_length=50)),
                ('Nominal', models.CharField(max_length=30)),
            ],
        ),
    ]
