# Generated by Django 4.1.3 on 2022-12-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0003_alter_gadai_bunga_per_th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadai',
            name='Nik',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
