# Generated by Django 4.1.3 on 2022-12-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0004_alter_gadai_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadai',
            name='Bunga_Per_Th',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
