# Generated by Django 4.1.3 on 2022-12-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0005_alter_gadai_bunga_per_th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadai',
            name='Bunga_Per_Th',
            field=models.BigIntegerField(null=True),
        ),
    ]
