# Generated by Django 4.1.3 on 2022-12-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('No_Tabungan', models.CharField(max_length=20)),
                ('Alamat', models.TextField()),
                ('Jumlah_tabungan', models.CharField(max_length=200)),
                ('Antrian', models.CharField(max_length=50)),
                ('Biaya_administrasi', models.CharField(max_length=20)),
            ],
        ),
    ]
